---
title: "jacaranda"
author: "berkeley_air_monitoring_group"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),Sys.Date(),'.html')) })

date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    self_contained: yes
---

```{r global_options, include=FALSE}
email = 1
timezone = 'GMT'
local_tz = 'Africa/Nairobi'
home_threshold_meters = 10 #meters


source('r_scripts/load.R')
source('r_scripts/plot_deployments.R')

dir.create("tester",showWarnings = F)
dir.create("odk data",showWarnings = F)  #Put odk data downloads into here.
dir.create("plots",showWarnings = F)
dir.create("processed data",showWarnings = F)
dir.create("QA Reports",showWarnings = F)
dir.create("results",showWarnings = F)
dir.create("~/Dropbox/Jacaranda Kenya Field Folder/Data/Plots/HHs with Amb",showWarnings = F)
dir.create("~/Dropbox/Jacaranda Kenya Field Folder/Data/Plots/maps",showWarnings = F)
knitr::opts_chunk$set(fig.path='../figures/', warning=FALSE, message=FALSE, cache=FALSE)

```


# Import GPS, PA, ODK data

```{r load_merge,cache=TRUE}
source('r_scripts/import_odk.R')
source('r_scripts/import_gps.R')
source('r_scripts/import_purpleair.R')

# set_key( "AIzaSyDUskJNHA7xGx6eTDg_dJdIvvlTPyIXdls", api = "geocode")
# set_key( "AIzaSyDUskJNHA7xGx6eTDg_dJdIvvlTPyIXdls", api = "map")
# google_keys()
# key <- Sys.getenv("google_maps_key")
# register_google(key)

# Merge GPS, PA data.  PA data should already be merged with ODK data.
#Merge PA data with ODK data
# pa_data = merge(pa_data,meta_merged, by.x=c("hhid"), by.y = c("hhid"))

#Plot each deployment's raw data
as.data.frame(pa_data) %>%
  dplyr::group_by(filename) %>%
  dplyr::do(f=plot_files(.))

as.data.frame(gps_data) %>%
  dplyr::group_by(filename) %>%
  dplyr::do(f=plotly_gps_files(.))

#Distance calculation constants
R = 6371e3 #meters - radius of earth
phi_fun = function(lat) {lat*pi/180}
phi_delta = function(lat1,lat2) {(lat1-lat2)*pi/180}
lambda_delta_fun = function(lon1,lon2) {(lon2-lon1)*pi/180}
x_fun = function(lambda_delta,phi){lambda_delta*cos(phi)}

#Merge data and clean it up
all_merged = merge(pa_data,
                   gps_data,
                   by=c('local_time','hhid'),all.x = TRUE,all.y = FALSE) %>% 
  dplyr::mutate(pa_file = basename(filename.x),
                gps_file = basename(filename.y),
                sampletype = ifelse(tolower(pa_file) %like% 'amb','ambient','personal'),
                gps_filled = ifelse(is.na(lat),1,0)) %>% 
  dplyr::rename(pa_id = instrument_id.x,
                gps_id = instrument_id.y) %>% 
  dplyr::filter(!hhid %like% "AMBIENT") %>%
  dplyr::filter(!filename.x %like% "Pilot") %>%
  dplyr::filter(!is.na(local_time),!is.infinite(local_time)) %>% 
  # Fill in time series down for GPS - seems appropriate for most cases based on time series plot of gps data.
  dplyr::group_by(sampletype, hhid) %>%
  fill(lat, .direction = "down") %>% 
  fill(lon, .direction = "down") %>% 
  dplyr::mutate(Mode_lat = getmode(lat),
                Mode_lon = getmode(lon),
                phi = phi_fun(lat),
                lambda_delta = lambda_delta_fun(lon,Mode_lon),
                x = x_fun(lambda_delta,phi),
                y = phi_delta(lat,Mode_lat),
                d_meters = R * sqrt(x^2 + y^2),
                home_flag = ifelse(d_meters < home_threshold_meters,1,0)) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(-lambda_delta,-phi,-x,-y,filesize_kb,-filename.y)

skimr::skim(all_merged)

```



# Summarize data
* Calculate distance metric from home (mode)
* What fraction of exposure happens at home?
* Get list of home GPSs, calculate fraction of exposure near there.

```{r summarize_data}

summary_by_activity <- all_merged %>% 
  dplyr::group_by(sampletype, hhid) 



summary_pa_deployment <- all_merged %>% 
  dplyr::group_by(sampletype, hhid) %>%
  dplyr::summarise(N_gps_samples = sum(!is.na(lat)), 
                   N_pa_samples = sum(!is.na(pm25_larpa_ave)),
                   N_hours = difftime(max(local_time,na.rm = T),
                                      min(local_time,na.rm = T),units = "hours"),
                   Min_pm25 = min(pm25_larpa_ave,na.rm = TRUE), 
                   Median_pm25 = median(pm25_larpa_ave,na.rm = TRUE),
                   Mean_pm25 = mean(pm25_larpa_ave,na.rm = TRUE), 
                   Max_pm25 = max(pm25_larpa_ave,na.rm = TRUE),
                   SD_pm25 = sd(pm25_larpa_ave,na.rm = TRUE),
                   Mode_lat = getmode(lat), 
                   Mode_lon = getmode(lon),
                   n_home = sum(home_flag == 1,na.rm = T),
                   n_away = sum(home_flag == 0,na.rm = T),
                   home_fraction = n_home/(n_home+n_away),
                   Mean_home_pm25 = mean(pm25_larpa_ave[home_flag==1],na.rm = TRUE),
                   Mean_away_pm25 = mean(pm25_larpa_ave[home_flag==0],na.rm = TRUE)) %>%
  dplyr::left_join(
    all_merged %>% 
      dplyr::select(pa_file,gps_file,pa_id,gps_id,hhid) %>% 
      dplyr::distinct() %>% 
      dplyr::arrange(pa_file,gps_file) %>% 
      dplyr::group_by(hhid) %>% 
      dplyr::filter(1== row_number()),
    by = "hhid")
knitr::kable(summary_pa_deployment, digits = 2, caption = "PurpleAir Summary Table","pipe")

summary_overall <- summary_pa_deployment %>% 
  dplyr::group_by(sampletype) %>%
  dplyr::summarise(N = n(), 
                   Min_pm25 = min(Min_pm25,na.rm = TRUE), 
                   Median_pm25 = median(Median_pm25,na.rm = TRUE),
                   Mean_pm25 = mean(Mean_pm25,na.rm = TRUE), 
                   Max_pm25 = max(Max_pm25,na.rm = TRUE),
                   SD_pm25 = sd(SD_pm25,na.rm = TRUE),
                   Mean_home_pm25 = mean(Mean_home_pm25,na.rm = TRUE),
                   Mean_away_pm25 = mean(Mean_away_pm25,na.rm = TRUE))
knitr::kable(summary_overall, digits = 2, caption = "PurpleAir Overall Summary Table")



```




# Plots
* Plot boxplots and scatter plots for exposures, HAP, ratios therein.
* Save html maps.

```{r boxplots_usage, fig.width=7, fig.height=4}

g_boxplot_distance <- summary_pa_deployment %>% 
  pivot_longer(cols = c("Mean_home_pm25","Mean_away_pm25")) %>% 
  ggplot(aes(x=name, y = value, colour = name)) +
  geom_boxplot(alpha = 0.25) +
  stat_summary(fun.y=mean, colour="blue", geom="point",
               shape=18, size=4.5,alpha = 0.5)+
  stat_summary(fun.data = give.mean, geom = "text",colour="blue") +
  geom_jitter(height = 0,width = 0.2,alpha = 0.25) +
  stat_summary(fun.data = give.n, geom = "text") +
  labs(y="Mean PM2.5 Concentration (ugm-3)",x="") +
  theme(legend.title = element_blank())
g_boxplot_distance

g_boxplot <- ggplot(summary_pa_deployment,aes(x=sampletype, y = Mean_pm25)) +
  geom_boxplot(alpha = 0.25) +
  stat_summary(fun.y=mean, colour="blue", geom="point",
               shape=18, size=4.5,alpha = 0.5)+
  stat_summary(fun.data = give.mean, geom = "text",colour="blue") +
  geom_jitter(height = 0,width = 0.2,alpha = 0.25) +
  stat_summary(fun.data = give.n, geom = "text") +
  labs(y="Mean PM2.5 Concentration (ugm-3)",x="") +
  theme(legend.title = element_blank())
g_boxplot

summary_wide <- tidyr::pivot_wider(summary_pa_deployment,
                                   id_cols = c('hhid','sampletype'),
                                   names_from = sampletype ,
                                   values_from = c('Mean_pm25','N_gps_samples'))

# # g_mother_child <- summary_wide %>% ggplot(aes(x=Mean_m, y = Mean_c)) +
# #   geom_point(alpha = 0.25) +  
# #   geom_abline(slope=1, intercept=0)+
# #   labs(y="Mean mother vs. child exposure",x="") + 
# #   theme(legend.title = element_blank())
# # g_mother_child

```


###Spatial Results
# Geo-spatial analysis
* Hot spots
```{r spatial_usage, fig.width=7, fig.height=4}

# # mapbase <- get_googlemap(center = c(mean(summary_pa_deployment$Mode_lon),mean(summary_pa_deployment$Mode_lat)), zoom = 12,
# #                          color = "color",
# #                          style = "feature:road|visibility:on&style=element:labels|visibility:on&style=feature:administrative|visibility:on")
# # #Map showing average exposure and median location. Different shape by sample type.
# # gg_ave <- ggmap(mapbase) +
# #   geom_point(data = summary_pa_deployment, aes(x = Mode_lon, y = Mode_lat, color=Mean,shape =sampletype))+
# #   scale_size_continuous(breaks = round) 
# # gg_ave <- ggplotly(gg_ave)

pal <- colorNumeric(
  palette = colorRampPalette(c('green', 'yellow','red'))(20),
  domain = c(0,300))

gg_ave <- leaflet() %>%
  addTiles() %>%  # use the default base map which is OpenStreetMap tiles
  # addProviderTiles(providers$Esri.WorldImagery) %>% #Test this baby out.
  addCircleMarkers(lng=summary_pa_deployment$Mode_lon, lat=summary_pa_deployment$Mode_lat,
                   popup=paste(summary_pa_deployment$hhid,', ',summary_pa_deployment$sampletype,', ', summary_pa_deployment$Mean_pm25),
                   # fillColor = all_merged$pm25_larpa_ave
                   radius =  (summary_pa_deployment$Mean_pm25+10)/10,
                   color = pal(summary_pa_deployment$Mean_pm25)
  )

saveWidget(gg_ave, '~/Dropbox/Jacaranda Kenya Field Folder/Data/Plots/maps/ave_map_jacaranda.html', selfcontained = T)

#Map with point per average deployment.


map_by_filedeployment <- function(all_merged,pal) {
  
  plot_name = paste0("~/Dropbox/Jacaranda Kenya Field Folder/Data/Plots/maps/map_",all_merged$hhid[1],".html")
  if(!file.exists(plot_name)){
    
    gg <- leaflet() %>%
      addTiles() %>%  # use the default base map which is OpenStreetMap tiles
      addProviderTiles(providers$Esri.WorldImagery) %>% #Test this baby out.
      addCircles(lng=all_merged$lon,
                 lat=all_merged$lat,
                 popup=paste(all_merged$local_time.x,', ',
                             all_merged$hhid,', ',all_merged$sampletype,', ', all_merged$pm25_larpa_ave),
                 fillColor = pal(all_merged$pm25_larpa_ave),
                 # radius =  (all_merged$pm25_larpa_ave+10)/10,
                 color = pal(all_merged$pm25_larpa_ave)
      )
    saveWidget(gg, plot_name, selfcontained = T)
  }
}

#Map for each deployment
#.001 degrees ~ 111m, .0001 degrees ~ 11.1m
all_merged %>%
  dplyr::group_by(hhid) %>%
  dplyr::do(a=map_by_filedeployment(.,pal))

all_merged %>%
  dplyr::mutate(hhid = "all") %>% 
  dplyr::do(a=map_by_filedeployment(.,pal))




```

# Ambient plots
```{r ambient_plots}

#Different plot for each household # 
# pa_data_temp <- all_merged %>% dplyr::filter(!hhid %like% "AMBIENT") 

#Plot each hhid
pa_ambient = all_merged %>% dplyr::filter(hhid %like% "Ambient")

all_merged %>% 
  dplyr::filter(!hhid %like% "Ambient") %>% 
  dplyr::group_by(hhid) %>%
  dplyr::do(f = plot_by_filedeployment(.,pa_ambient))


```


# Save data
```{r save_data}

#Write summary stats to an excel workbook
list_of_datasets <- list("Deployment Summary" = summary_pa_deployment,
                         "Overall Summary" = summary_overall)
openxlsx::write.xlsx(list_of_datasets, file = paste0("../results/Summary Statistics ",format(now(),"%d-%b-%y"),".xlsx"))


saveRDS(all_merged,file="processed data/all_merged.RDS")
write.xlsx(all_merged,file="processed data/all_merged.xlsx")

list_of_datasets <- list(
  "PurpleAir and GPS"=summary_pa_deployment,
  "summary_overall" = summary_overall
)

filename = paste0("QA Reports/QA_PA_GPS_ODK_",Sys.Date(),".xlsx")

write.xlsx(list_of_datasets,file = filename)

source('r_scripts/emailfun.R')
# emailfun(email,filename)

```
